AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceName:
    Type: String
    Default: MyFirstInstance
Resources:
  PhoneNumber:
    Type: AWS::Connect::PhoneNumber
    Properties:
      Description: Phone number created using cfn
      CountryCode: US
      TargetArn:
        Fn::ImportValue: MyFirstInstance
      Type: DID
Outputs:
  ConnectPhoneNumber:
    Value:
      Ref: PhoneNumber
    Export:
      Name:
        Fn::Sub: ${InstanceName}PhoneNumber
  ConnectPhoneNumberAddress:
    Value:
      Fn::GetAtt:
      - PhoneNumber
      - Address
    Export:
      Name:
        Fn::Sub: ${InstanceName}PhoneNumberAddress
  ConnectPhoneNumberPhoneNumberArn:
    Value:
      Fn::GetAtt:
      - PhoneNumber
      - PhoneNumberArn
    Export:
      Name:
        Fn::Sub: ${InstanceName}PhoneNumberPhoneNumberArn
