AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceName:
    Type: String
    Default: MySecondInstance
Resources:
  ConnectInstance2:
    Type: AWS::Connect::Instance
    Properties:
      Attributes:
        AutoResolveBestVoices: true
        ContactflowLogs: true
        ContactLens: true
        InboundCalls: true
        OutboundCalls: true
      InstanceAlias:
        Fn::Sub: ${AWS::AccountId}-${AWS::Region}-${InstanceName}
      IdentityManagementType: CONNECT_MANAGED

  InstanceHoursOfOperation2:
    Type: AWS::Connect::HoursOfOperation
    Properties:
      Description: Hours of Operation
      InstanceArn:
        Fn::GetAtt:
        - ConnectInstance2
        - Arn
      Name: Hours of Operation Mon - Friday
      Tags:
      - Key: developer
        Value: awesomedeveloper
      TimeZone: America/New_York
      Config:
      - Day: MONDAY
        StartTime:
          Hours: 10
          Minutes: 0
        EndTime:
          Hours: 16
          Minutes: 59
      - Day: TUESDAY
        StartTime:
          Hours: 10
          Minutes: 0
        EndTime:
          Hours: 16
          Minutes: 59
      - Day: WEDNESDAY
        StartTime:
          Hours: 10
          Minutes: 0
        EndTime:
          Hours: 16
          Minutes: 59
      - Day: THURSDAY
        StartTime:
          Hours: 10
          Minutes: 0
        EndTime:
          Hours: 16
          Minutes: 59
      - Day: FRIDAY
        StartTime:
          Hours: 10
          Minutes: 0
        EndTime:
          Hours: 16
          Minutes: 59
Outputs:
  ConnectInstanceArn:
    Value:
      Fn::GetAtt:
      - ConnectInstance2
      - Arn
    Description: My first Amazon Connect Instance
    Export:
      Name:
        Ref: InstanceName
  ConnectInstanceCreatedTime:
    Value:
      Fn::GetAtt:
      - ConnectInstance2
      - CreatedTime
  ConnectInstanceServiceRole:
    Value:
      Fn::GetAtt:
      - ConnectInstance2
      - ServiceRole
  ConnectInstanceAlias:
    Value:
      Fn::Sub: ${AWS::AccountId}-${AWS::Region}-${InstanceName}
    Export:
      Name:
        Fn::Sub: ${InstanceName}Alias
  ConnectInstanceName:
    Value:
      Ref: InstanceName
    Export:
      Name: ConnectInstanceName
